/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "k8s.io/sample-controller/pkg/apis/genericdaemon/v1beta1"
)

// FakeGenericdaemons implements GenericdaemonInterface
type FakeGenericdaemons struct {
	Fake *FakeMydomainV1beta1
	ns   string
}

var genericdaemonsResource = v1beta1.SchemeGroupVersion.WithResource("genericdaemons")

var genericdaemonsKind = v1beta1.SchemeGroupVersion.WithKind("Genericdaemon")

// Get takes name of the genericdaemon, and returns the corresponding genericdaemon object, and an error if there is any.
func (c *FakeGenericdaemons) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Genericdaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(genericdaemonsResource, c.ns, name), &v1beta1.Genericdaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Genericdaemon), err
}

// List takes label and field selectors, and returns the list of Genericdaemons that match those selectors.
func (c *FakeGenericdaemons) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GenericdaemonList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(genericdaemonsResource, genericdaemonsKind, c.ns, opts), &v1beta1.GenericdaemonList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GenericdaemonList{ListMeta: obj.(*v1beta1.GenericdaemonList).ListMeta}
	for _, item := range obj.(*v1beta1.GenericdaemonList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested genericdaemons.
func (c *FakeGenericdaemons) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(genericdaemonsResource, c.ns, opts))

}

// Create takes the representation of a genericdaemon and creates it.  Returns the server's representation of the genericdaemon, and an error, if there is any.
func (c *FakeGenericdaemons) Create(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.CreateOptions) (result *v1beta1.Genericdaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(genericdaemonsResource, c.ns, genericdaemon), &v1beta1.Genericdaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Genericdaemon), err
}

// Update takes the representation of a genericdaemon and updates it. Returns the server's representation of the genericdaemon, and an error, if there is any.
func (c *FakeGenericdaemons) Update(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (result *v1beta1.Genericdaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(genericdaemonsResource, c.ns, genericdaemon), &v1beta1.Genericdaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Genericdaemon), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGenericdaemons) UpdateStatus(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (*v1beta1.Genericdaemon, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(genericdaemonsResource, "status", c.ns, genericdaemon), &v1beta1.Genericdaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Genericdaemon), err
}

// Delete takes name of the genericdaemon and deletes it. Returns an error if one occurs.
func (c *FakeGenericdaemons) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(genericdaemonsResource, c.ns, name, opts), &v1beta1.Genericdaemon{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGenericdaemons) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(genericdaemonsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GenericdaemonList{})
	return err
}

// Patch applies the patch and returns the patched genericdaemon.
func (c *FakeGenericdaemons) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Genericdaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(genericdaemonsResource, c.ns, name, pt, data, subresources...), &v1beta1.Genericdaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Genericdaemon), err
}
