/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "k8s.io/sample-controller/pkg/apis/genericdaemon/v1beta1"
	scheme "k8s.io/sample-controller/pkg/generated_test/clientset/versioned/scheme"
)

// GenericdaemonsGetter has a method to return a GenericdaemonInterface.
// A group's client should implement this interface.
type GenericdaemonsGetter interface {
	Genericdaemons(namespace string) GenericdaemonInterface
}

// GenericdaemonInterface has methods to work with Genericdaemon resources.
type GenericdaemonInterface interface {
	Create(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.CreateOptions) (*v1beta1.Genericdaemon, error)
	Update(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (*v1beta1.Genericdaemon, error)
	UpdateStatus(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (*v1beta1.Genericdaemon, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Genericdaemon, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.GenericdaemonList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Genericdaemon, err error)
	GenericdaemonExpansion
}

// genericdaemons implements GenericdaemonInterface
type genericdaemons struct {
	client rest.Interface
	ns     string
}

// newGenericdaemons returns a Genericdaemons
func newGenericdaemons(c *MydomainV1beta1Client, namespace string) *genericdaemons {
	return &genericdaemons{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the genericdaemon, and returns the corresponding genericdaemon object, and an error if there is any.
func (c *genericdaemons) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Genericdaemon, err error) {
	result = &v1beta1.Genericdaemon{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("genericdaemons").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Genericdaemons that match those selectors.
func (c *genericdaemons) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GenericdaemonList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.GenericdaemonList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("genericdaemons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested genericdaemons.
func (c *genericdaemons) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("genericdaemons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a genericdaemon and creates it.  Returns the server's representation of the genericdaemon, and an error, if there is any.
func (c *genericdaemons) Create(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.CreateOptions) (result *v1beta1.Genericdaemon, err error) {
	result = &v1beta1.Genericdaemon{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("genericdaemons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genericdaemon).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a genericdaemon and updates it. Returns the server's representation of the genericdaemon, and an error, if there is any.
func (c *genericdaemons) Update(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (result *v1beta1.Genericdaemon, err error) {
	result = &v1beta1.Genericdaemon{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("genericdaemons").
		Name(genericdaemon.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genericdaemon).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *genericdaemons) UpdateStatus(ctx context.Context, genericdaemon *v1beta1.Genericdaemon, opts v1.UpdateOptions) (result *v1beta1.Genericdaemon, err error) {
	result = &v1beta1.Genericdaemon{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("genericdaemons").
		Name(genericdaemon.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genericdaemon).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the genericdaemon and deletes it. Returns an error if one occurs.
func (c *genericdaemons) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("genericdaemons").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *genericdaemons) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("genericdaemons").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched genericdaemon.
func (c *genericdaemons) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Genericdaemon, err error) {
	result = &v1beta1.Genericdaemon{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("genericdaemons").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
